# Generated by Django 4.2.7 on 2023-12-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255)),
                ('phone_number', models.BigIntegerField()),
                ('room_id', models.IntegerField()),
                ('date_arrived', models.DateField(auto_now=True)),
            ],
        ),
    ]
