# Generated by Django 4.2.7 on 2023-12-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='occupany',
            new_name='occupancy',
        ),
    ]
